[[redirects]]
  from = "/api/*"
  to = "http://3.108.1.211.nip.io:9000/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ws-notifications/*"
  to = "http://3.108.1.211.nip.io:9000/ws-notifications/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ws-collab/*"
  to = "http://3.108.1.211.nip.io:9000/ws-collab/:splat"
  status = 200
  force = true

# This ensures React Router works on refresh
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
